### ISSUE TITLE
stable diffusion的版本可能太低了？

### ISSUE THREAD

**Issue by loser10085** [SRInternet-Studio/Wallpaper-generator#1]
可以参考使用stable diffusion更高的版本吗？感觉参考v1生成的很多时候反向标签大多时候没啥用啊，人体结构不自然。

**Comment by SRInternet** [comment]
### 开发部回复
感谢您的提议！我们已经受到了您的提议并准备商讨。您可以直接联系联系 @jiangyin14 （QQ：1219439938）直接与我们面对面交流噢！也欢迎您加入官方QQ群，与我们相关部门负责技术人员交流

**Comment by jiangyin14** [comment]
感谢您的建议。
